### ISSUE TITLE
Generator crashes at runtime, likely related to unsupported code in the shader

### ISSUE THREAD

**Issue by morphinapg** [Sergio0694/ComputeSharp#226]
### Description (optional)

When converting code I had written in an older version of a project to work with ComputeSharp, I had placed some methods in my shader struct. The project would build, but then at run time, when the shader was called, I would get this error:

`System.NotImplementedException: 'The method or operation is not implemented.'`

```
   at ComputeSharp.__Internals.IShader.GetDispatchId() in /_/src/ComputeSharp/Core/Interfaces/__Internals/IShader.cs:line 22
   at ComputeSharp.Shaders.Loading.PipelineDataLoader`1.GetPipelineData(GraphicsDevice device, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader) in /_/src/ComputeSharp/Shaders/Loading/PipelineDataLoader{T}.cs:line 38
   at ComputeSharp.ComputeContext.Run[T](Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader) in /_/src/ComputeSharp/Shaders/ComputeContext.cs:line 210
   at ComputeSharp.ComputeContext.Run[T](Int32 x, Int32 y, Int32 z, T& shader) in /_/src/ComputeSharp/Shaders/ComputeContext.cs:line 169
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, Int32 y, T& shader) in /_/src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Dispatching.cs:line 43
   at Test.Form1.AnalyzeImages_GPU() in C:\Users\morph\source\repos\Test\Test\Form1.cs:line 20
   at Test.Form1..ctor() in C:\Users\morph\source\repos\Test\Test\Form1.cs:line 11
   at Test.Program.Main() in C:\Users\morph\source\repos\Test\Test\Program.cs:line 14
```

### Reproduction Steps

This code will result in the crash: (Winforms project with .NET 6.0)

[Test.zip](https://github.com/Sergio0694/ComputeSharp/files/8481797/Test.zip)

I figured out that the main issue with this appears to be the Convert.ToSingle, which I'm assuming is not supported in a shader. I have since modified my methods to work entirely with floats. 

Originally, I thought the problem was with including methods in the struct (thinking I needed to define them outside the struct with the [ShaderMethod] attribute), I later realized that I could include them if I modified them to remove the conversion. 

The methods were originally designed entirely around doubles when it was CPU code, and I was figuring if I did the calculations with double precision math first, and then converted them to floats before returning, the result would be just a little more precise (sort of like how it's best to round things at the final step), but since I ended up using floats in the texture objects, I ended up just getting rid of that conversion to just have the whole workflow be float.

### Expected Behavior

If the project builds (which it did), I would expect it to run, or at least point out which thing I did that wasn't supported.

### Actual Behavior

The app builds and runs, but crashes when the shader is called, with the above error. I've been told this is a bug in the generator and shouldn't happen, even if the code in the shader is unsupported.

### System info

This section should contain useful info such as:
- ComputeSharp NuGet version 2.0.0-alpha.20
- Windows 11 21H2
- CPU: AMD Ryzen 7 2700X
- GPU: Nvidia RTX 3080 Ti
- Visual Studio Community 2022 Version 17.0.5
- .NET 6.0

**Comment by Sergio0694** [comment]
Hey, thank you for the report! That's correct, the issue was `Convert.ToSingle` isn't support. Shaders can only use either intrinsics (ie. all methods from the `Hlsl` class), or methods that have source availabe, so they can be converted as well. That wasn't the case for `Convert.ToSingle`, so the generator was failing, here:

https://github.com/Sergio0694/ComputeSharp/blob/3de7ebeb75648213d504e75e66c45bc6d7917294/src/ComputeSharp.SourceGenerators/SyntaxRewriters/ShaderSourceRewriter.cs#L407-L409

The reason being there were no syntax references to look up. I've added special handling for this so that now the generator will produce a proper error instead of just crashing, informing users that that method is just not supported from a shader.

This is fixed in cdf11ec79c7efbdadb804405d7d1a71c5c5c58d0.

Thanks!
