### ISSUE TITLE
Shaders are compiled at runtime despite having `[D2DEmbeddedBytecode(...)]`

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#282]
This is from the latest alpha off the public nuget feed, _not_ the nightly build.

This seems to be affecting all of my shaders, _at least on ARM64_. I don't know if they're being compiled at runtime on x64. I ran into this crash that is due to https://github.com/dotnet/wpf/issues/5462, which I can fix by just not packaging D3DCompiler_47.dll with my app (I don't need it since I'm targeting Win10+). But, with the crash gone, why are the shaders being compiled at runtime? 🤔

Here's one of the shaders:

```cs
[D2DInputCount(3)]
[D2DInputSimple(0)]
[D2DInputDescription(0, D2D1Filter.MinMagMipPoint)]
[D2DInputSimple(1)]
[D2DInputDescription(1, D2D1Filter.MinMagMipPoint)]
[D2DInputSimple(2)]
[D2DInputDescription(2, D2D1Filter.MinMagMipPoint)]
[D2DPixelOptions(D2D1PixelOptions.TrivialSampling)]
[D2DEmbeddedBytecode(D2D1ShaderProfile.PixelShader40Level91)]
private readonly partial struct OverwriteCompositeShader
    : IPixelShader<OverwriteCompositeShader>
{
    static IPixelShaderTransformImpl IPixelShader<OverwriteCompositeShader>.CreateTransform(in OverwriteCompositeShader shader)
    {
        return PixelShaderTransforms.CreateDefault(shader);
    }

    public float4 Execute()
    {
        float4 dst = D2D.GetInput(0);
        float4 src = D2D.GetInput(1);
        float4 srcMask = D2D.GetInput(2);
        float4 result = ((1 - srcMask) * dst) + (srcMask * src);
        return result;
    }
}
```

And here's the exception I'm getting, which I had to snag by hooking `AppDomain.FirstChanceException` :

```
Exception details:
System.TypeInitializationException: The type initializer for 'ShaderCacheHelper`1' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'D3DCompile' in DLL 'd3dcompiler_47'.
   at TerraFX.Interop.DirectX.DirectX.D3DCompile(Void* , UIntPtr , SByte* , D3D_SHADER_MACRO* , Void* , SByte* , SByte* , UInt32 , UInt32 , ID3DBlob** , ID3DBlob** )
   at ComputeSharp.D2D1.Shaders.Translation.D2D1ShaderCompiler.CompileD2DFullShader(ReadOnlySpan`1 , D2D1ShaderProfile )
   at ComputeSharp.D2D1.Shaders.Translation.D2D1ShaderCompiler.Compile(ReadOnlySpan`1 , D2D1ShaderProfile , Boolean )
   at ComputeSharp.D2D1.__Internals.D2D1ShaderCompiler.LoadDynamicBytecode[TLoader,T](TLoader& , T& , Nullable`1 , Boolean )
   at PaintDotNet.Direct2D1.Effects.OverwriteCompositeEffect.OverwriteCompositeShader.global::ComputeSharp.D2D1.__Internals.ID2D1Shader.LoadBytecode[TLoader](TLoader& loader, Nullable`1 shaderProfile) in D:\src\pdn\src\Windows.Framework\ComputeSharp.D2D1.SourceGenerators\ComputeSharp.D2D1.SourceGenerators.ID2D1ShaderGenerator\PaintDotNet.Direct2D1.Effects.OverwriteCompositeEffect.OverwriteCompositeShader.LoadBytecode.cs:line 21
   at ComputeSharp.D2D1.Interop.D2D1ReflectionServices.GetShaderInfo[T]()
   at PaintDotNet.Direct2D1.Effects.D2D1PixelShaderUtil.ShaderCacheHelper`1..cctor() in D:\src\pdn\src\Windows.Framework\Direct2D1\Effects\D2D1PixelShaderUtil.cs:line 54
   --- End of inner exception stack trace ---
   at PaintDotNet.Direct2D1.Effects.D2D1PixelShaderUtil.GetCachedInputDescriptions[TShader]() in D:\src\pdn\src\Windows.Framework\Direct2D1\Effects\D2D1PixelShaderUtil.cs:line 21
```

**Comment by Sergio0694** [comment]
Yeah pretty sure I've fixed this already (IIRC it was some flags being passed wrong which re-triggered the build), though I can find the exact commit where I fixed that right now. I've opened #283 to add more tests to ensure we can spot regressions 🙂
