### ISSUE TITLE
2 for loops with same loop variable name cannot be compiled

### ISSUE THREAD

**Issue by Kloizdena** [Sergio0694/ComputeSharp#557]
### Description (optional)

I was trying to write 2 for loops in my shader in the form `for (int i = 0; i < _buffer.Length; i++) { ... }`.
When I try to run the shader, it throws an exception that the generated shader code cannot be compiled.

### Reproduction Steps

Run the following code in a console app:

```csharp
IComputeShader shader = new LoopTest();
shader.BuildHlslSource(out var builder, 0, 0, 0);
Console.WriteLine(builder.WrittenSpan.ToString());
var device = GraphicsDevice.GetDefault();
using var buffer = device.AllocateReadWriteBuffer<float4>(1);
device.For(1, new LoopTest(buffer));

[AutoConstructor]
public readonly partial struct LoopTest : IComputeShader
{
    private readonly ReadWriteBuffer<float4> _buffer;

    public void Execute()
    {
        for (int i = 0; i < _buffer.Length; i++)
        {
            _buffer[i] = i;
        }
        for (int i = 0; i < _buffer.Length; i++)
        {
            _buffer[i] = i;
        }
    }
}
```

### Expected Behavior

The shader should be compiled and run without error.

### Actual Behavior

The following exception is thrown at runtime:
```
The DXC compiler encountered one or more errors while trying to compile the shader:

error: redefinition of 'i' shadows declaration in the outer scope; most recent declaration will be used [-Werror,-Wfor-redefinition]
        for (int i = 0; i < __get_Dimension0(_buffer); i++)
                 ^
note: previous definition is here
        for (int i = 0; i < __get_Dimension0(_buffer); i++)
                 ^
.

Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp.
If you're sure that your C# shader code is valid, please open an issue an include a working repro and this error message.



   at ComputeSharp.Shaders.Translation.ShaderCompiler.ThrowHslsCompilationException(IDxcOperationResult* dxcOperationResult) in /_/src/ComputeSharp.Dynamic/Shaders/Translation/ShaderCompiler.cs:line 171
   at ComputeSharp.Shaders.Translation.ShaderCompiler.Compile(ReadOnlySpan`1 source) in /_/src/ComputeSharp.Dynamic/Shaders/Translation/ShaderCompiler.cs:line 138
   at ComputeSharp.__Internals.ShaderCompiler.LoadDynamicBytecode[TLoader,T](TLoader& loader, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader) in /_/src/ComputeSharp.Dynamic/Shaders/Translation/__Internals/ShaderCompiler.cs:line 32
   at LoopTest.global::ComputeSharp.__Internals.IShader.LoadBytecode[TLoader](TLoader& loader, Int32 threadsX, Int32 threadsY, Int32 threadsZ) in C:\src\WinUITest\CompilationTest\ComputeSharp.SourceGenerators\ComputeSharp.SourceGenerators.IShaderGenerator\LoopTest.LoadBytecode.g.cs:line 12
   at ComputeSharp.Shaders.Loading.PipelineDataLoader`1.LoadShader(Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader, ICachedShader& shaderData)
   at ComputeSharp.Shaders.Loading.PipelineDataLoader`1.GetPipelineData(GraphicsDevice device, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader)
   at ComputeSharp.ComputeContext.Run[T](Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader)
   at ComputeSharp.ComputeContext.Run[T](Int32 x, T& shader)
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, T& shader)
   at Program.<Main>$(String[] args) ...

```

The following code is generated for the shader:

```c++
// ================================================
//                  AUTO GENERATED
// ================================================
// This shader was created by ComputeSharp.
// See: https://github.com/Sergio0694/ComputeSharp.

#define __GroupSize__get_X 0
#define __GroupSize__get_Y 0
#define __GroupSize__get_Z 0

cbuffer _ : register(b0)
{
    uint __x;
    uint __y;
    uint __z;
}

RWStructuredBuffer<float4> _buffer : register(u0);

static int __get_Dimension0(RWStructuredBuffer<float4> resource);

static int __get_Dimension0(RWStructuredBuffer<float4> resource)
{
    uint _0, _1;
    resource.GetDimensions(_0, _1);
    return _0;
}

[NumThreads(__GroupSize__get_X, __GroupSize__get_Y, __GroupSize__get_Z)]
void Execute(uint3 ThreadIds : SV_DispatchThreadID)
{
    if (ThreadIds.x < __x && ThreadIds.y < __y && ThreadIds.z < __z)
    {
        for (int i = 0; i < __get_Dimension0(_buffer); i++)
        {
            _buffer[i] = i;
        }

        for (int i = 0; i < __get_Dimension0(_buffer); i++)
        {
            _buffer[i] = i;
        }
    }
}
```

### System info

- **ComputeSharp.Dynamic** NuGet version: 2.0.3
- Operating system version: Microsoft Windows [Version 10.0.22621.2134]
- CPU/GPU model (the latter is especially useful for shader issues): AMD Ryzen 7 5825U
- Visual Studio version Version 17.7.0, .NET SDK version 7.0.400

**Comment by Sergio0694** [comment]
This seems to just be a bug in the older version of DXC, tried now and it seems to work 😄
Probably fixed by #639. I'd suggest trying out a new preview build from the preview feed!
