### ISSUE TITLE
calling static method throws

### ISSUE THREAD

**Issue by Redninja106** [Sergio0694/ComputeSharp#74]
I am trying to run the "Advanced Usage" example in Readme.md but it throws an `System.InvalidOperationException`. Any call to a static method throws this same exception. Thanks for the help in advance!
My default Gpu is an RTX 2060.

Here is the exception info:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at ComputeSharp.Shaders.Translation.MethodDecompiler.GetSyntaxTreeForStaticMethod(MethodInfo methodInfo)
   at ComputeSharp.Shaders.Translation.MethodDecompiler.GetSyntaxTree(MethodInfo methodInfo, MethodType methodType, MethodDeclarationSyntax& rootNode, SemanticModel& semanticModel)
   at ComputeSharp.Shaders.Translation.ShaderLoader`1.LoadStaticMethodSource(Object shader, String name, MethodInfo methodInfo)
   at ComputeSharp.Shaders.Translation.ShaderLoader`1.LoadMethodSource(Object shader)
   at ComputeSharp.Shaders.Translation.ShaderLoader`1.Load(T& shader)
   at ComputeSharp.Shaders.ShaderRunner`1.LoadShader(Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader, CachedShader`1& shaderData)
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, Int32 threadsX, Int32 threadsY, Int32 threadsZ, T& shader)
   at ComputeSharp.Shaders.ShaderRunner`1.Run(GraphicsDevice device, Int32 x, Int32 y, Int32 z, T& shader)
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, Int32 y, T& shader)
```

**Comment by Sergio0694** [comment]
Hey, thanks for the report!
I could repro this, and this is definitely a regression - used to work just fine.
I'll look into fixing this during the new rewrite for `2.0`, thanks! 😄

**Comment by Sergio0694** [comment]
Closing this as there is a new preview build on NuGet for ComputeSharp 2.0 that doesn't have this issue anymore 🙂
