### ISSUE TITLE
Running the sample app on .NET 9 throws `MissingFieldException` "Field not found: '{Shader}.<buffer>P'"

### ISSUE THREAD

**Issue by Peter-Juhasz** [Sergio0694/ComputeSharp#893]
### Reproduction Steps

Run "Hello world" based on https://github.com/Sergio0694/ComputeSharp/wiki/3.-Getting-started-%F0%9F%93%96 to multiply numbers in an array at once.

Or the sample app: https://github.com/Sergio0694/ComputeSharp/blob/120aff270539996ef9fc52fe46561d12da0b89d4/samples/ComputeSharp.Sample/Program.cs

### Expected Behavior

The sample runs without any error just like on .NET 8.0.

### Actual Behavior

```
Unhandled exception. System.MissingFieldException: Field not found: 'GpuLinq.MultiplyByTwo.<buffer>P'.
   at ComputeSharp.Generated.<GpuLinq_MultiplyByTwo_g>FBE22A9B254E8C5B4C31CB0BF8C793133B000321365754432B0E19EFB843B68E0__GraphicsResourcesLoader.buffer(MultiplyByTwo& value)
   at GpuLinq.MultiplyByTwo.global::ComputeSharp.Descriptors.IComputeShaderDescriptor<GpuLinq.MultiplyByTwo>.LoadGraphicsResources[TLoader](MultiplyByTwo& shader, TLoader& loader) in S:\git\disposable\GpuLinq\obj\Debug\net9.0\ComputeSharp.SourceGenerators\ComputeSharp.SourceGenerators.ComputeShaderDescriptorGenerator\GpuLinq.MultiplyByTwo.g.cs:line 102
   at ComputeSharp.ComputeContext.Run[T](Int32 x, Int32 y, Int32 z, T& shader) in /_/src/ComputeSharp/Shaders/ComputeContext.cs:line 178
   at ComputeSharp.ComputeContext.Run[T](Int32 x, T& shader) in /_/src/ComputeSharp/Shaders/ComputeContext.cs:line 127
   at ComputeSharp.GraphicsDeviceExtensions.For[T](GraphicsDevice device, Int32 x, T& shader) in /_/src/ComputeSharp/Graphics/Extensions/GraphicsDeviceExtensions.Dispatching.cs:line 26
   at GpuLinq.Program.Main(String[] args) in S:\git\disposable\GpuLinq\Program.cs:line 15
```

### System info

This section should contain useful info such as:
- **ComputeSharp** NuGet version (or branch/commit, if building from source): 3.1.0
- Operating system version: 26100.2605
- CPU/GPU model (the latter is especially useful for shader issues): NVIDIA GeForce RTX 4060 TI
- Visual Studio version, or .NET SDK/runtime version: 17.13 P2.1 + .NET 9.0.100

**Comment by Sergio0694** [comment]
This is a known issue caused by a bug in .NET 9 (https://github.com/dotnet/runtime/issues/109943). It's also the reason why #871 is currently still a draft. We fixed the issue in .NET 9 (and I've added some regression tests for this scenario specifically), but the fix hasn't been released yet. It should be out in .NET 9.0.2xx, which should be out sometime in February I think.

**Comment by Sergio0694** [comment]
This is fixed with the .NET 9.0.102 SDK, which was released last week.

**Comment by Sergio0694** [comment]
Nevermind, it's not actually fixed in 9.0.102, reopening 🥲

**Comment by xiaoyuvax** [comment]
met the same problem. waiting for fix confirmation.

**Comment by Sergio0694** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/111675. The fix will be in 9.0.3xx (out in early March).

**Comment by Sergio0694** [comment]
This is now resolved in .NET 9.0.3 (SDK version 9.0.202), closing this 🙂
